# Generated by Django 4.0.3 on 2022-04-13 16:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_product_price_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
